export { default as ArrowLeftShort } from './ArrowLeftShort'
export { default as Calendar } from './Calendar'
export { default as Clock } from './Clock'
export { default as People } from './People'
export { default as Wallet } from './Wallet'